services:
  wishes-service:
    build:
      context: .
    container_name: wishes-service
    networks:
      - kafka-network
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: "mongodb+srv://klosenico00:fWca0BFR6fXmSQZI@xmaswishes.slyyj.mongodb.net/?retryWrites=true&w=majority&appName=Xmaswishes"
      KAFKA_BROKER: "kafka:9092"

networks:
  kafka-network:
    external: true
