services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    networks:
      - kafka-network
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - kafka-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - kafka-network
    ports:
      - "27017:27017"

  wishes-service:
    build:
      context: ./xmaswishes-backend
    container_name: wishes-service
    networks:
      - kafka-network
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: "mongodb+srv://klosenico00:fWca0BFR6fXmSQZI@xmaswishes.slyyj.mongodb.net/?retryWrites=true&w=majority&appName=Xmaswishes"
      KAFKA_BROKER: "kafka:9092"
    depends_on:
      - kafka
      - mongo
      - zookeeper

  elf-service:
    build:
      context: ./elf-service
    container_name: elf-service
    networks:
      - kafka-network
    environment:
      MONGO_URI: "mongodb+srv://klosenico00:fWca0BFR6fXmSQZI@xmaswishes.slyyj.mongodb.net/?retryWrites=true&w=majority&appName=Xmaswishes"
      KAFKA_BROKER: "kafka:9092"
    depends_on:
      - kafka
      - mongo
      - zookeeper

  # frontend:
  #   build:
  #     context: ./xmaswishes-frontend
  #   container_name: xmaswishes-frontend
  #   networks:
  #     - kafka-network
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - wishes-service
  #   environment:
  #     BACKEND_URL: "http://wishes-service:4000"

networks:
  kafka-network:
    name: kafka-network
    driver: bridge
