version: "3.8"
services:
  elf-service:
    build:
      context: .
    container_name: elf-service
    networks:
      - kafka-network

    environment:
      MONGO_URI: "mongodb+srv://klosenico00:fWca0BFR6fXmSQZI@xmaswishes.slyyj.mongodb.net/?retryWrites=true&w=majority&appName=Xmaswishes"
      KAFKA_BROKER: "kafka:9092"

networks:
  kafka-network:
    external: true
